services:
  opensearch:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: opensearch
    environment:
      - DISABLE_SECURITY_PLUGIN=true
      - bootstrap.memory_lock=true  # along with the memlock settings below, disables swapping
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m  # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - plugins.security.ssl.http.enabled=true
      - discovery.type=single-node
      - script.painless.regex.enabled=true
      # - opensearch_security.disabled=true

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      # - opensearch_security.disabled=true
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
